version: '3'

services:

  # Swaggerをブラウザで編集するためのコンテナ：Swagger-Editor版
  sample-swagger-editor:
    image: swaggerapi/swagger-editor
    volumes:
      - ./swagger:/tmp
    environment:
      SWAGGER_JSON: "/tmp/openapi-doc.yaml"
    ports:
      - '8001:8080'

  # Swaggerをブラウザでプレビューするためのコンテナ：Swagger-UI版
  sample-swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/tmp
    environment:
      SWAGGER_JSON: "/tmp/openapi-doc.yaml"
    ports:
      - '8002:8080'

  # Swaggerをブラウザでプレビューするためのコンテナ：Redoc版
  sample-redoc:
    image: redocly/redoc
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      SPEC_URL: ./swagger/openapi-doc.yaml
      PORT: 8080
    ports:
      - '8003:8080'

